Fix: 検索バーのモーダル化
Pluspo/pluspo pull request #144
Opened 2023-01-26 04:27 UTC by yoshihiro-hy

## 概要

close #140
- スマホで見た時にヘッダーの検索バーが入りきらないのでモーダル化して対応しました
### ヘッダー検索ボタン
[![Image from Gyazo](https://i.gyazo.com/474d9fe5085f1e9193955441026fbf66.png)](https://gyazo.com/474d9fe5085f1e9193955441026fbf66)
### モーダルの中身
[![Image from Gyazo](https://i.gyazo.com/9211920ac389aec7a636a74d7cc0d7a3.png)](https://gyazo.com/9211920ac389aec7a636a74d7cc0d7a3)
## 確認方法

1. TOPページにアクセス
2. ヘッダーに「検索」ボタンが表示されることを確認
3. 検索ボタンをクリック
4. モーダルが表示されて検索ができることを確認
5. 適当に検索してみて検索結果が表示されるか確認
6. 検証ツールでスマホ対応しているか確認

## 影響範囲
- ヘッダー

## チェックリスト

- [ ] rubocopをパスした
- [ ] rspecをパスした

2023-01-26 05:01 UTC, mayuyuyuyunn requested changes
app/assets/builds の中身消してください！！
tailwindの名残ですw
https://github.com/Pluspo/pluspo/pull/129

2023-01-26 05:39 UTC, yoshihiro-hy commented
本当ですね笑

2023-02-01 01:19 UTC, yoshiki105 approved these changes
イメージ通りで完璧です！
細かい点ですがコメントしました！
ここ直してもらったらLGTMです！

2023-02-01 01:19 UTC, yoshiki105 commented on app/views/shared/_search_schedule_form.html.slim
> +        button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
ここも。

2023-02-01 01:19 UTC, yoshiki105 commented on app/views/shared/_search_schedule_form.html.slim
> +button type="button" class="btn btn-outline-success" data-bs-toggle="modal" data-bs-target="#exampleModal"
classとidはslimの記法で書きましょう！

2023-02-01 01:19 UTC, yoshiki105 commented on app/views/shared/_search_schedule_form.html.slim
> +.modal.fade id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
ここも。

2023-02-01 05:57 UTC, mayuyuyuyunn approved these changes
LGTMですん。

2023-02-01 05:59 UTC, yoshihiro-hy commented on app/views/shared/_search_schedule_form.html.slim
> +.modal.fade id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"
ちょっと待ってくださいね〜

2023-02-02 10:58 UTC, yoshiki105 approved these changes
コメントしました〜
直したらpushしてマージしちゃってください！

2023-02-02 10:58 UTC, yoshiki105 commented on app/views/shared/_search_schedule_form.html.slim
> +        button.btn-close data-bs-dismiss="modal" aria-label="Close"
`type="button"`はあったほうが良いのでは...🤔？

2023-02-02 11:17 UTC, merged