Add: gem bullet #13
Pluspo/pluspo pull request #30
Opened 2022-08-26 07:20 UTC by mayuyuyuyunn

## 概要

gem bulletの導入
[公式](https://github.com/flyerhzm/bullet#run-in-tests)と[参考記事](https://qiita.com/sazumy/items/7157446d7c3bfe377d63)
をみてdevelopment環境にのみ導入しました。

## 確認方法
1. Gem を追加したので `bundle install` を実行してください。

## コメント
test環境にもインストール必要であれば修正します！

2022-08-26 21:25 UTC, yoshiki105 requested changes
めちゃくちゃ細かいところですがコメントしました🙇‍♂️
あと、1番上の概要文？のところに対応するIssueの Closes の追加もお願いします！

2022-08-26 21:25 UTC, yoshiki105 commented on Gemfile
> +  # gem bulletを追加
積み重なっていくとごちゃごちゃしちゃうのでコメント行は消しちゃいましょう！

2022-08-27 02:05 UTC, yoshihiro-hy approved these changes
LGTMです！

2022-08-27 02:43 UTC, 0417-hub approved these changes
LGTMです！ありがとうございます！

2022-08-27 06:25 UTC, mayuyuyuyunn commented on Gemfile
> +  # gem bulletを追加
コメント削除しました。確認お願いします。

2022-08-27 07:02 UTC, yoshiki105 approved these changes
LGTMです！

2022-08-27 07:05 UTC, merged